server:
  port: 8777
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/monitor?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: admin
  data:
    redis:
      database: 0
  threads:
    virtual:
      enabled: true
#      username:
#      password:

fileserver:
  root: D:Project/JavaProjekte/PG/monitor-backend/file
  prefix: "http://127.0.0.1/file"



mybatis-flex:
  global-config:
    print-banner: off