CREATE TABLE IF NOT EXISTS `monitor_behavior_analysis` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `exam_id` int(11) NOT NULL COMMENT '考试ID',
  `examinee_account_id` int(11) NOT NULL COMMENT '考生账号ID',
  `student_id` int(11) DEFAULT NULL COMMENT '学生ID',
  `event_type` int(11) NOT NULL COMMENT '行为事件类型: 1-切屏, 2-切换程序, 3-异常操作, 4-违规软件, 5-截图异常, 6-网站异常, 7-其他',
  `content` varchar(500) NOT NULL COMMENT '行为内容',
  `event_time` datetime NOT NULL COMMENT '发生时间',
  `level` varchar(20) NOT NULL DEFAULT 'info' COMMENT '风险等级: info-信息, warning-警告, danger-严重, success-成功',
  `screenshot_id` int(11) DEFAULT NULL COMMENT '相关截图ID',
  `related_id` int(11) DEFAULT NULL COMMENT '相关数据ID',
  `related_type` varchar(50) DEFAULT NULL COMMENT '相关数据类型',
  `is_processed` tinyint(1) DEFAULT '0' COMMENT '是否已处理 0-否 1-是',
  `process_result` varchar(500) DEFAULT NULL COMMENT '处理结果',
  `process_time` datetime DEFAULT NULL COMMENT '处理时间',
  `processor_id` int(11) DEFAULT NULL COMMENT '处理人ID',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_exam_id` (`exam_id`),
  KEY `idx_examinee_account_id` (`examinee_account_id`),
  KEY `idx_student_id` (`student_id`),
  KEY `idx_event_time` (`event_time`),
  KEY `idx_event_type` (`event_type`),
  KEY `idx_level` (`level`),
  KEY `idx_is_processed` (`is_processed`),
  KEY `idx_screenshot_id` (`screenshot_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='考生行为分析记录表'; 